### ISSUE TITLE
`hsm push` (all-scripts invocation) does not follow symbolic links

### ISSUE THREAD

**Issue by danswann** [samualtnorman/hackmud-script-manager#155]
If you have a script symlinked to a different location, you can push it on its own explicitly, i.e.:
```bash
hsm push src myuser.symlinked_script
```
but if you run the global push
```bash
hsm push
```
any symlinked scripts are not discovered.

**Comment by danswann** [comment]
`hsm push myuser.*` also fails, while `hsm push *.symlinked_script` succeeds.

**Comment by samualtnorman** [comment]
ty for reporting

**Comment by samualtnorman** [comment]
please can you try `pnpm add hackmud-script-manager@0.19.1-3ef8894`.
I've updated `hsm push` (and only `hsm push atm)

**Comment by danswann** [comment]
Fixed in all mentioned cases for `hsm push`.

**Comment by samualtnorman** [comment]
nice! I'll apply the same changes else where and then close this issue
