### ISSUE TITLE
$s. does not get transformed to correct scriptspace

### ISSUE THREAD

**Issue by Braste** [samualtnorman/hackmud-script-manager#168]
When I use $s. to call scripts, it gets transformed to #fs. in the result js file, even if the called script has another seclevel. This example can be used to reproduce it:
```
// @seclevel MIDSEC
export default (_context: Context, args: unknown) => {
    $s.chats.join({channel:""});
}
```
It results in
`function(){#fs.chats.join({channel:""})}`
despite chat.join is midsec.
Omiting // @seclevel MIDSEC does not change the result.

**Comment by Braste** [comment]
Update:
When i usse two scripts, one with $fs.script1 and one with $ms.script2 both scripts will become #ms. That brings some seccurity risks when you call scripts from other users and do not want them to be called, if they are not fs, for example.

**Comment by samualtnorman** [comment]
I've been thinking about it, I don't think I'm gonna fix this.
instead I think wanna deprecate and then remove `$s.`.
`$s.`'s existence is a foot-gun (it was removed and replaced with explicit seclevels in hackmud for a reason)

**Comment by samualtnorman** [comment]
I am open to re-opening this issue. If you reading this found this issue and you want this, feel free to comment and I can re-open it
