### ISSUE TITLE
Destructured `args` parameter name gets wrongfully minified into a comment

### ISSUE THREAD

**Issue by rijenkii** [samualtnorman/hackmud-script-manager#169]
Initial script:
```javascript
function (
  _,
  { really_long_parameter_name_that_should_not_be_minified_into_a_comment },
) {
  return really_long_parameter_name_that_should_not_be_minified_into_a_comment;
}
```
Command used:
```
npx hsm golf test.js /dev/stdout
```
Minified:
```javascript
function($,{[e]:t}){
//	really_long_parameter_name_that_should_not_be_minified_into_a_comment	
let e=#fs.scripts.quine().split`	`[1]
return t}
```
The generated code fails to execute, because `e` is referenced before its creation.

**Comment by samualtnorman** [comment]
interesting, tank you for reporting

**Comment by samualtnorman** [comment]
I've implemented a fix. Please can you confirm the fix by installing the `@dev` version of HSM?
- If you are using Hackmud Scripting Environment, run `pnpm add hackmud-script-manager@dev`
- If you have HSM installed globally, run `npm install -g hackmud-script-manager@dev`

**Comment by rijenkii** [comment]
Yep, works.

**Comment by samualtnorman** [comment]
ty
