### ISSUE TITLE
Golfing incorrectly escapes (s and )s

### ISSUE THREAD

**Issue by Argonius-Angelus** [samualtnorman/hackmud-script-manager#178]
I'm dealing with a big lack of sleep here while writing this, but much like #172 there's some seriously odd behavior that can emerge when golfing a script that contains `scripts.quine` in some form, as well as strings like "e)(ecutioner". This breaks the JSON parser for some reason. 

Basically, if (s or )s exist inside the cheated strings, don't escape them, as for some reason that makes them transcend the string itself and murders the parser.  As soon as I removed the \s escaping the (s and )s within those strings, it stopped erroring.

**Comment by samualtnorman** [comment]
please can you give a minimal reproduction? thanks

**Comment by Argonius-Angelus** [comment]
```js
function(context,args){
    args = args || {}
	if (args.name == "testing"){
        return #fs.scripts.quine()
    }
}
```

when hsm golf is run on it spits out
```js
function(t,$){
//	["name","testing","function(context,args){\n    args = args || {}\n\tif (args.name == \"testing\"){\n        return #fs.scripts.quine\()\n    }\n}"]	
let[e,s,i]=JSON.parse(#fs.scripts.quine().split`	`[1])
if(($=$||{})[e]==s)return i}
```

This, when run regardless of params, should cause the following error to appear `:::TRUST COMMUNICATION::: SyntaxError: Unexpected token ( in JSON at position 134` 
This is because the ( in `#fs.scripts.quine()` is being escaped.

**Comment by samualtnorman** [comment]
ah, good catch

**Comment by samualtnorman** [comment]
I've added a fix.

You can install the `@dev` version of the package to test if the fix works:
- If you have HSM installed globally, update it with `npm install -g hackmud-script-manager@dev`
- Or if you're using Hackmud Scripting Environment, run this in the folder `pnpm add hackmud-script-manager@dev`

If you then afterwards want to return to the latest proper release, run the same command again but replace `@dev` with `@latest`.
