### ISSUE TITLE
Some cool types are no longer accessible to HSE/HSM end users

### ISSUE THREAD

**Issue by danswann** [samualtnorman/hackmud-script-manager#221]
I was migrating from the version of HSE that had `hackmud.d.ts` in the root directory to the modern version where the hackmud types are bundled with HSM, and I noticed I don't get stuff like `Upgrade` or any of the Mongo-related types (`MongoDocument`, `MongoQuery`, etc.) anymore.

Was this deliberate, and if not: is the solution just to throw everything into the `declare global` scope?

**Comment by samualtnorman** [comment]
yeah it was intentional because there were a lot of types that were just an implementation detail and should not have been relied on by users. I do not mind making certain types public though if it makes sense.

are you able to make a list of types you rely on?

thanks

**Comment by danswann** [comment]
If most of them are implementation details then I think the correct answer is for me to stop relying on them.

The hardest part for me is coming from my database library, which wrapped the builtin `$db` stuff, especially w.r.t. inferring custom Mongo document structures. I'm having trouble understanding how to do it with the new defs (although this might be a separate issue).

E.g.
![image](https://github.com/user-attachments/assets/242abf5e-b8d0-4b14-a139-67ff6f281be9)
```
src/lib/common.ts:20:50 - error TS2322: Type '{ $gte: number; }' is not assignable to type 'number'.

20 const test1 = $db.f<MyCustomDocumentWithValue>({ value: { $gte: 5 } }).first();
                                                    ~~~~~

  src/lib/common.ts:18:52
    18 type MyCustomDocumentWithValue = { type: "custom"; value: number } & BaseMongoDocument;
                                                          ~~~~~
    The expected type comes from property 'value' which is declared here on type 'MyCustomDocumentWithValue'

src/lib/common.ts:21:15 - error TS2352: Conversion of type '({ [k: string]: MongoValue; } & { value: unknown; }) | null' to type 'MyCustomDocumentWithValue' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ [k: string]: MongoValue; } & { value: unknown; }' is not comparable to type 'MyCustomDocumentWithValue'.
    Property 'type' is missing in type '{ [k: string]: MongoValue; } & { value: unknown; }' but required in type '{ type: "custom"; value: number; }'.

21 const test2 = $db.f({ value: { $gte: 5 } }).first() as MyCustomDocumentWithValue;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/lib/common.ts:18:36
    18 type MyCustomDocumentWithValue = { type: "custom"; value: number } & BaseMongoDocument;
                                          ~~~~
    'type' is declared here.


Found 2 errors in the same file, starting at: src/lib/common.ts:20
```
