### ISSUE TITLE
Problems with `_id` in `MongoProject` (and thus `$db.f`)

### ISSUE THREAD

**Issue by danswann** [samualtnorman/hackmud-script-manager#222]
[TypeScript Playground link](https://www.typescriptlang.org/play/?#code/PQKgUABCEGIE4HsC2ECmA7AbgOgCbYBcBnSEYMMYYCXAQwNoCNajUwCBPAB1QgHlGAK1QBjAgElcEALwQA3hAAkCAJa4AXBCIE4K9AHMIAX3bdeAWQQGEABV1IVBFZl6z0AVwA2niAB8IjAgInqi06H4QHkiMqHARACL0vP7augamPBCW1gBqtJ7urllW+rb2js7Jxbn5hQDaALoR2aUCwmIZFiUIbaIEMvIQdQDWmql6+g2aLQh5BagANEOjEAAGiopy4wZGq1ORqC5xJpyZM5IDAKIAHiIFuKgAPDN2Kg5OLkse3gB8zd29DqUagAfTUEBURAg+QA7rQOFC4KgCO44OhUFJ3OgQkQoWCNBAAGb5VgQqFcFisXDAiAwgAWGGh6A4MBUqE8BJ0hTJEH0lXQSwQBAZcUJbI5UIAFKhbqguP18QBKaFIiDIRwEDEUU5dax2BDtAiPAAq8QQIncSAwBCWxv1hpUVj+0jAAEgubwZZr0LgpQBGNDXb2+iB2xAOqwjVAcBCE0P2vqO9BNAD8EA9EE0YYNicjw2jsfj4dzyeVKbdrsl2Yj4S9GBDCnxmmJnlJ-gADMYIGm5EZM4Mm6GzRareh+nWfVDG2pNHpCbFQxc+2njRdpt0l8qAGQV11yXeuuoAaQh6APrvzMbjpvNlut0KhJ4nIcvherJe7RZzYiTx6az6hDN-ADNMT00dEjn7CDYgPfYbxHa0-13Psd1dND9zQtCAFokVoXArE8DghhPPRz1fa8Ex-KwHy-Gs-0DYNALgblgM-J8g3rKFyKHW9R36NNoLiTQwIOI5YJTdcanmZC3U0BQRjGHQJn2GY5m5FDBmPU8IG4+C7zHGj2MYnSCwo4sqPCATDgXYS4OHfSCHokwKFAUgIAAYXcbRkAgEQEAeUhyE6CB4gAIVZH0ACVUCILx+lkF5zKNOQLW8pAj2jdQohiOAjCWXsfgAbhc6hxH6Ig6QQLwpBiCAuAQXEVEYEIiQQOJVnxVZ0wQAJeDCNZAQkXBVjAPz0G0QMeDEDF1DCiLcGi2LPHi+RBzkZQZwAIgANgAdm2wkACZaD9U7dtwP0AGZTsYQ7Lu2gAOEQAE48M2vLfK8ghkDU1B1AAViMYqaTKrRKuqyIhV6uqGqIJqWsJNq1k67rodWb5PC6rCsIgJtzikSFIf6GIJjQdBEbgEQtSoUM6UJ-RkShMVrgxWkGXCYVeC4JKkx5dArCw1AkHlDgllQbB9GwGkdVDGKVsS79ktS770sy7LYg+lKvuQDKOHUP0jB+GkAAFiEF64poIQW4EQOBRqsCbmA0Oa9AWmK4oGOQmwxpZlZ1zLAcKoA)

`_id` is supposed to always be constrained to `MongoId`, but there are two problems:
1. `_id` is not constrained to `MongoId` when the projection is empty
1. `MongoId` does not include `ObjectId`, which should be a valid value for `_id`

**Comment by samualtnorman** [comment]
okay, I've made a change. please could you try it out by installing the `@dev` version. thanks.

**Comment by danswann** [comment]
Updated to `0.21.1-2086872`.
Seems to have fixed <span>#</span>2 but not <span>#</span>1.
![image](https://github.com/user-attachments/assets/7610d267-f5cf-41a4-aee2-32ce64ed4c72)

**Comment by danswann** [comment]
You did the hard part, so I tried to fix the other thing in #223.

**Comment by samualtnorman** [comment]
ty, I have made yet another change. I did rename `ObjectId` to `MongoObjectId` since I didn't realise what it was at first which meant its name needed to be more explicit. please could you try now? thanks

**Comment by danswann** [comment]
LGTM
